### ISSUE TITLE
crash on file with only comments

### ISSUE THREAD

**Issue by andreineculau** [kentcdodds/babel-plugin-preval#31]
- `babel-plugin-preval` version: 1.4.2

I have a file that was commented out in its entirety, and then `babel-plugin-preval` crashes with

```
TypeError: src/aws-elb.js: Cannot read property 'leadingComments' of undefined
    at PluginPass.Program (/Users/andrei/git/firecloud/aws-cfn-util-firecloud/node_modules/babel-plugin-preval/dist/index.js:26:41)
    at newFn (/Users/andrei/git/firecloud/aws-cfn-util-firecloud/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/andrei/git/firecloud/aws-cfn-util-firecloud/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/andrei/git/firecloud/aws-cfn-util-firecloud/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/andrei/git/firecloud/aws-cfn-util-firecloud/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/andrei/git/firecloud/aws-cfn-util-firecloud/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/andrei/git/firecloud/aws-cfn-util-firecloud/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/andrei/git/firecloud/aws-cfn-util-firecloud/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/andrei/git/firecloud/aws-cfn-util-firecloud/node_modules/babel-traverse/lib/index.js:114:17)
    at traverse (/Users/andrei/git/firecloud/aws-cfn-util-firecloud/node_modules/babel-traverse/lib/index.js:79:12)
```

**Comment by kentcdodds** [comment]
I believe this has been fixed. Could you upgrade?

If not, please dig a little deeper and feel free to [make a pull request](http://makeapullrequest.com) :+1:

Thanks!
