### ISSUE TITLE
Preval fails when using imported vars

### ISSUE THREAD

**Issue by bluepnume** [kentcdodds/babel-plugin-preval#35]
- `babel-plugin-preval` version: 1.5.0
- `node` version: 6.11.2
- `npm` (or `yarn`) version: 3.10.10

Works:

```javascript
let foo = 'bar';

let result = preval`
    module.exports = "${ foo }";
`;
```

Fails with `Unable to determine the value of your preval string`:

```javascript
import { foo } from './foo';

let result = preval`
    module.exports = "${ foo }";
`;
```

What you did:

Tried to include an imported variable into a preval string

What happened:

Error thrown:

```bash
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./src/components/button/templates/component/style/base.js
Module build failed: Error: /Users/dbrain/paypal-checkout/src/components/button/templates/component/style/base.js: Unable to determine the value of your preval string
    at PluginPass.TaggedTemplateExpression (/Users/dbrain/paypal-checkout/node_modules/babel-plugin-preval/dist/index.js:54:17)
    at newFn (/Users/dbrain/paypal-checkout/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/dbrain/paypal-checkout/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/dbrain/paypal-checkout/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/dbrain/paypal-checkout/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/dbrain/paypal-checkout/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/dbrain/paypal-checkout/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/dbrain/paypal-checkout/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/dbrain/paypal-checkout/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/dbrain/paypal-checkout/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/dbrain/paypal-checkout/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/dbrain/paypal-checkout/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/dbrain/paypal-checkout/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/dbrain/paypal-checkout/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/dbrain/paypal-checkout/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/dbrain/paypal-checkout/node_modules/babel-traverse/lib/context.js:150:16)
 @ ./src/components/button/templates/component/style/index.js 5:12-29
 @ ./src/components/button/templates/component/template.js
 @ ./src/components/button/templates/component/index.js
 @ ./src/components/button/templates/index.js
 @ ./src/components/button/component.jsx
 @ ./src/components/button/index.js
 @ ./src/components/index.js
 @ ./src/interface.js
 @ ./src/index.js
 @ ./src/load.js
```

**Comment by bluepnume** [comment]
(Understood totally, by the way, if this is expected behavior / outside the scope of what preval is intended to do)

**Comment by kentcdodds** [comment]
Hey! 👋

Right now we just use babel's built-in mechanism for statically evaluating expressions, and it is only so powerful.

But I built one here that is a bit more powerful: https://github.com/kentcdodds/css-in-js-precompiler/blob/master/src/get-literalizers.js

If you want to see if that would work here. Let me know...
