### ISSUE TITLE
Using preval without evaling code imported with require().default

### ISSUE THREAD

**Issue by mbrookes** [kentcdodds/babel-plugin-preval#49]
* `babel-plugin-preval` version: ^1.6.2
* `node` version: v8.9.4
* `npm` (or `yarn`) version: yarn v1.3.2

Relevant code or config

```javascript
const myObject = preval`
result = {}
const fullPath = 'some/derived/path/to/file.js'
result[fullpath] = {
    js: require(fullPath).default,
}
`
```
Where the value of js is the `require`'d code to be eval'd in the running app.

What you did:

Ran a more complete example on multiple paths in an Array.reduce()

What happened:

```
ERROR in ./pages/utils/transitions.js
Module build failed: /Users/matthew.brookes/Projects/material-ui/docs/src/pages/utils/transitions/SimpleCollapse.js:1
(function (exports, require, module, __filename, __dirname) { import React from 'react';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at reducer (/Users/matthew.brookes/Projects/material-ui/pages/utils/transitions.js:10:9)
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (/Users/matthew.brookes/Projects/material-ui/pages/utils/transitions.js:15:29)
    at Module._compile (module.js:643:30)
    at requireFromString (/Users/matthew.brookes/Projects/material-ui/node_modules/require-from-string/index.js:28:4)
    at getReplacement (/Users/matthew.brookes/Projects/material-ui/node_modules/babel-plugin-preval/dist/get-replacement.js:18:13)
    at PluginPass.TaggedTemplateExpression (/Users/matthew.brookes/Projects/material-ui/node_modules/babel-plugin-preval/dist/index.js:56:27)
 @ multi ./pages/utils/transitions.js
```

Where:

`/Users/matthew.brookes/Projects/material-ui/docs/src/pages/utils/transitions/SimpleCollapse.js`

is the file being required

`import React from 'react'`

is the first line of that file.

`/Users/matthew.brookes/Projects/material-ui/pages/utils/transitions.js`

is the file containing preval.

Reproduction repository:

I don't have a minimal version to share, but you could 
```sh
git clone clone https://github.com/mui-org/material-ui.git
yarn
yarn start
```
Then replace `pages/utils/transitions.js` with this: https://gist.github.com/mbrookes/e933031d378ce7169d9f21a774330a11

Problem description:

preval  evals code imported with `require().default`

Thanks! 🌟

**Comment by kentcdodds** [comment]
So are you saying that you'd rather generate code than values? If that's the case you should look at preval's cousin [`codegen`](https://github.com/kentcdodds/babel-plugin-codegen) :)

As it is, I don't think this issue is actionable, so I'm going to go ahead and close it. If you think there's a bug or would like to make a feature request, please dig a little further and make a suggestion of what you'd like changed. Thanks!
