### ISSUE TITLE
Usage with 'babel-plugin-module-resolver'

### ISSUE THREAD

**Issue by chrstntdd** [kentcdodds/babel-plugin-preval#76]
- `babel-plugin-preval` version: 4.0.0
- `node` version: 12.14.0
- `npm` (or `yarn`) version: 6.13.4

Relevant code or config

```javascript
// usage
const URLS = preval`
  const { pureFunc } = require("@my/aliased/path");
  const url1 = pureFunc(...args)
  const url2 = pureFunc(...args);
  module.exports = {url1, url2}
`;
```

```javascript
// .babelrc.js
{
  plugins: [
  [
    'babel-plugin-module-resolver',
    {
      alias: {
        '@my': './some/rel/path',
      }
    }
  ],
  '@babel/plugin-proposal-nullish-coalescing-operator',
  '@babel/plugin-proposal-optional-chaining',
  IS_DEVELOPMENT && '@babel/plugin-transform-react-jsx-source',
  '@babel/plugin-proposal-class-properties',
  '@babel/plugin-syntax-dynamic-import',
  'preval'
].filter(Boolean),
...
}
```

What you did:
Attempted to use preval where the require path uses an alias.

What happened:

```shell
Error: /path/to/project/src/MyComponent/data.ts: Cannot find module '@my/aliased/path'
Require stack:
- /path/to/project/src/MyComponent/data.ts
- /path/to/project/node_modules/babel-plugin-preval/dist/helpers.js
- /path/to/project/node_modules/babel-plugin-preval/dist/index.js
- /path/to/project/node_modules/@babel/core/lib/config/files/plugins.js
- /path/to/project/node_modules/@babel/core/lib/config/files/index.js
- /path/to/project/node_modules/@babel/core/lib/index.js
- /path/to/project/scripts/make-server.ts
- /path/to/project/scripts/main.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/path/to/project/src/MyComponent/data.ts:2:32)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at requireFromString (/path/to/project/node_modules/require-from-string/index.js:28:4)
    at requireFromString (/path/to/project/node_modules/babel-plugin-preval/dist/helpers.js:21:13)
    at getReplacement (/path/to/project/node_modules/babel-plugin-preval/dist/helpers.js:39:15)
    at PluginPass.TaggedTemplateExpression (/path/to/project/node_modules/babel-plugin-preval/dist/index.js:79:29) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/path/to/project/src/MyComponent/data.ts',
    '/path/to/project/node_modules/babel-plugin-preval/dist/helpers.js',
    '/path/to/project/node_modules/babel-plugin-preval/dist/index.js',
    '/path/to/project/node_modules/@babel/core/lib/config/files/plugins.js',
    '/path/to/project/node_modules/@babel/core/lib/config/files/index.js',
    '/path/to/project/node_modules/@babel/core/lib/index.js',
    '/path/to/project/scripts/make-server.ts',
    '/path/to/project/scripts/main.ts'
  ]
}
```

Problem description:
Looks like the application of the plugins is such that the `babel-plugin-module-resolver` plugin is not applying the transformations to the code that is being preevaluated. I know that there are lots of things to consider when possibly evaluating the string passed to `preval`, but I wasn't sure if this was something that's possible.

Suggested solution:
Seems out of scope of this project, but I can only fathom that the right way to get this to work would have the alias plugin be applied before the code is `preval`'d such that the relative path is available for the `preval` step. 

My other thought is that this might have to be its own macro? Would definitely appreciate some pointers on how something like this would be accomplished. It seems like compromising the aliasing is not something that our project would be willing to do. Thank you for you time and this project.

Cheers!

**Comment by kentcdodds** [comment]
Hi @chrstntdd,

You're analysis of the situation is correct, and I'm sorry but this is outside the scope of the project. I don't want to get into compiling the prevalled code. Sorry. And good luck!
